# Generated by Django 5.1.7 on 2025-04-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpa_payment_id',
            new_name='razorpay_payment_id',
        ),
    ]
